FROM mongo:latest

# Define mountable directories.
VOLUME ["/data/db"]

# Define working directory.
WORKDIR /data

# Define default command.
CMD ["mongod"]

# Expose ports.
#   - 2701from pymongo import MongoClient7: process
#   - 28017: http
EXPOSE 27017
EXPOSE 28017
