version: "3"
services:
  nginx:
    restart: always
    build:
      context: "./nginx"
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf:/etc/nginx/
      - ./nginx/log:/var/log/nginx
      - ./nginx/static-html-directory:/usr/share/nginx/html/
  mongodb:
    build: 
      context: "./mongodb"
      dockerfile: Dockerfile    
    ports:
      - "27017:27017"      
      - "28017:28017"
    volumes:
      - ./mongodb/data:/data/db
  
